wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1666001417.342064
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.7.13
      5: 0.13.3
      8:
      - 8
action_dim:
  desc: null
  value: 9
adam_beta:
  desc: null
  value: 0.9
batch_size:
  desc: null
  value: 256
cond_decode:
  desc: null
  value: true
data:
  desc: null
  value:
    dataset_spec:
      crop_rand_subseq: true
      dataset_class: proposed.data.kitchen.src.kitchen_data_loader.D4RLGoalRelabelingDataset
      env_name: kitchen-mixed-v0
      max_seq_len: 280
      n_actions: 9
      res: 128
      state_dim: 60
      subseq_len: 11
    device: cpu
    subseq_len: 11
data_dir:
  desc: null
  value: .
early_stop_rounds:
  desc: null
  value: 100
epoch_cycles_train:
  desc: null
  value: 50
epochs:
  desc: null
  value: 50
evaluator:
  desc: null
  value: null
exp_path:
  desc: null
  value: null
gc:
  desc: null
  value: true
gradient_clip:
  desc: null
  value: null
hidden_dim:
  desc: null
  value: 128
init_grad_clip:
  desc: null
  value: 0.001
init_grad_clip_step:
  desc: null
  value: 100
kl_div_weight:
  desc: null
  value: 0.0005
latent_dim:
  desc: null
  value: 10
log_path:
  desc: null
  value: ./log.txt
logger:
  desc: null
  value: null
lr:
  desc: null
  value: 0.001
model_cls:
  desc: null
  value: null
model_id:
  desc: null
  value: ''
momentum:
  desc: null
  value: 0
n_env:
  desc: null
  value: 21
n_obj:
  desc: null
  value: 9
n_processing_layers:
  desc: null
  value: 5
n_rollout_steps:
  desc: null
  value: 10
optim_cls:
  desc: null
  value: torch.optim.adam.Adam
prior_loss:
  desc: null
  value: nll
project:
  desc: null
  value: gcspirl
reg_beta:
  desc: null
  value: 0.0005
save_ckpt:
  desc: null
  value: 0
save_path:
  desc: null
  value: ./weights
schedulerClass:
  desc: null
  value: torch.optim.lr_scheduler.ReduceLROnPlateau
scheduler_params:
  desc: null
  value:
    cooldown: 0
    eps: 1.0e-08
    factor: 0.2
    min_lr: 1.0e-12
    mode: min
    patience: 4
    threshold: 0.01
    threshold_mode: abs
    verbose: true
state_dim:
  desc: null
  value: 60
target_kl:
  desc: null
  value: 0.0005
top_comp_metric:
  desc: null
  value: mse
top_of_n_eval:
  desc: null
  value: 100
val_data_size:
  desc: null
  value: 5000
warmup_method:
  desc: null
  value: null
warmup_steps:
  desc: null
  value: 20
